// Code generated by furo-proto-gen. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: syrius/common/syrius_ui_common.proto

package commonpb

import (
	fat "github.com/theNorstroem/FuroBaseSpecs/dist/pb/furo/fat"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BigText type specification with annotation support
type BigText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Fat String
	Text *fat.String `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *BigText) Reset() {
	*x = BigText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BigText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigText) ProtoMessage() {}

func (x *BigText) ProtoReflect() protoreflect.Message {
	mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigText.ProtoReflect.Descriptor instead.
func (*BigText) Descriptor() ([]byte, []int) {
	return file_syrius_common_syrius_ui_common_proto_rawDescGZIP(), []int{0}
}

func (x *BigText) GetText() *fat.String {
	if x != nil {
		return x.Text
	}
	return nil
}

// Represents a SYRIUS business object reference.
type BoReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifier of the business object.
	Id *Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Localized string representation.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Target client url. SYRIUS client push or web url.
	Url *Url `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *BoReference) Reset() {
	*x = BoReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoReference) ProtoMessage() {}

func (x *BoReference) ProtoReflect() protoreflect.Message {
	mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoReference.ProtoReflect.Descriptor instead.
func (*BoReference) Descriptor() ([]byte, []int) {
	return file_syrius_common_syrius_ui_common_proto_rawDescGZIP(), []int{1}
}

func (x *BoReference) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BoReference) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *BoReference) GetUrl() *Url {
	if x != nil {
		return x.Url
	}
	return nil
}

// Represents a SYRIUS code item.
type Code struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Universal Unique Identifier of the code item.
	Id *BoReference `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Internal name of the code item.
	InternalName string `protobuf:"bytes,2,opt,name=internal_name,json=internalName,proto3" json:"internal_name,omitempty"`
	// short form of the code item description.
	ShortForm string `protobuf:"bytes,3,opt,name=short_form,json=shortForm,proto3" json:"short_form,omitempty"`
	// Code header reference.
	Parent *BoReference `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *Code) Reset() {
	*x = Code{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Code) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Code) ProtoMessage() {}

func (x *Code) ProtoReflect() protoreflect.Message {
	mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Code.ProtoReflect.Descriptor instead.
func (*Code) Descriptor() ([]byte, []int) {
	return file_syrius_common_syrius_ui_common_proto_rawDescGZIP(), []int{2}
}

func (x *Code) GetId() *BoReference {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Code) GetInternalName() string {
	if x != nil {
		return x.InternalName
	}
	return ""
}

func (x *Code) GetShortForm() string {
	if x != nil {
		return x.ShortForm
	}
	return ""
}

func (x *Code) GetParent() *BoReference {
	if x != nil {
		return x.Parent
	}
	return nil
}

// SYRIUS code list
type CodeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Code header reference.
	Id *BoReference `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// list of available codes within a head
	CodeList []*Code `protobuf:"bytes,5,rep,name=code_list,json=codeList,proto3" json:"code_list,omitempty"`
}

func (x *CodeList) Reset() {
	*x = CodeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeList) ProtoMessage() {}

func (x *CodeList) ProtoReflect() protoreflect.Message {
	mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeList.ProtoReflect.Descriptor instead.
func (*CodeList) Descriptor() ([]byte, []int) {
	return file_syrius_common_syrius_ui_common_proto_rawDescGZIP(), []int{3}
}

func (x *CodeList) GetId() *BoReference {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CodeList) GetCodeList() []*Code {
	if x != nil {
		return x.CodeList
	}
	return nil
}

// Represents a SYRIUS identifier.
type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// String representation of the id value.
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Additional meta information.
	MetaId int64 `protobuf:"varint,2,opt,name=meta_id,json=metaId,proto3" json:"meta_id,omitempty"`
	// Originating system from where the ID comes.
	Origin string `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_syrius_common_syrius_ui_common_proto_rawDescGZIP(), []int{4}
}

func (x *Id) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Id) GetMetaId() int64 {
	if x != nil {
		return x.MetaId
	}
	return 0
}

func (x *Id) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

// Syrius language definition
type Language struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identity of the language
	Id *Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the Language
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Language tag, RFC-3066
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *Language) Reset() {
	*x = Language{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_syrius_common_syrius_ui_common_proto_rawDescGZIP(), []int{5}
}

func (x *Language) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Language) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Language) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type SubTenant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id of the tenant/subtenant
	Id *Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 2-digit char initials of the tenant/subtenant
	Initials string `protobuf:"bytes,2,opt,name=initials,proto3" json:"initials,omitempty"`
	// Localized short designation of the tenant/subtenant
	ShortForm string `protobuf:"bytes,3,opt,name=short_form,json=shortForm,proto3" json:"short_form,omitempty"`
	// Localized description of the tenant/subtenant
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Defines the background color. Possible values are; Accent1 to Accent10
	SemanticColor string `protobuf:"bytes,5,opt,name=semantic_color,json=semanticColor,proto3" json:"semantic_color,omitempty"`
	// Is this a global subtenant? Global subtenants can be used with non-global subtenants. Non-global subtenants cannot be used with other non-global subtenants.
	IsGlobal bool `protobuf:"varint,6,opt,name=is_global,json=isGlobal,proto3" json:"is_global,omitempty"`
}

func (x *SubTenant) Reset() {
	*x = SubTenant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubTenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubTenant) ProtoMessage() {}

func (x *SubTenant) ProtoReflect() protoreflect.Message {
	mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubTenant.ProtoReflect.Descriptor instead.
func (*SubTenant) Descriptor() ([]byte, []int) {
	return file_syrius_common_syrius_ui_common_proto_rawDescGZIP(), []int{6}
}

func (x *SubTenant) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SubTenant) GetInitials() string {
	if x != nil {
		return x.Initials
	}
	return ""
}

func (x *SubTenant) GetShortForm() string {
	if x != nil {
		return x.ShortForm
	}
	return ""
}

func (x *SubTenant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubTenant) GetSemanticColor() string {
	if x != nil {
		return x.SemanticColor
	}
	return ""
}

func (x *SubTenant) GetIsGlobal() bool {
	if x != nil {
		return x.IsGlobal
	}
	return false
}

// SYRIUS user definition
type SyrUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identity of the SyrUser
	Id *Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name of the SyrUser
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// 2-digit char initials of the SyrUser
	Initials string `protobuf:"bytes,3,opt,name=initials,proto3" json:"initials,omitempty"`
}

func (x *SyrUser) Reset() {
	*x = SyrUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyrUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyrUser) ProtoMessage() {}

func (x *SyrUser) ProtoReflect() protoreflect.Message {
	mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyrUser.ProtoReflect.Descriptor instead.
func (*SyrUser) Descriptor() ([]byte, []int) {
	return file_syrius_common_syrius_ui_common_proto_rawDescGZIP(), []int{7}
}

func (x *SyrUser) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SyrUser) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SyrUser) GetInitials() string {
	if x != nil {
		return x.Initials
	}
	return ""
}

// Url type specification
type Url struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Url according https://url.spec.whatwg.org/#urls
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Text if displayed as link
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Forces the client to open in new window.
	ForceBlank bool `protobuf:"varint,3,opt,name=force_blank,json=forceBlank,proto3" json:"force_blank,omitempty"`
}

func (x *Url) Reset() {
	*x = Url{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_syrius_common_syrius_ui_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_syrius_common_syrius_ui_common_proto_rawDescGZIP(), []int{8}
}

func (x *Url) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Url) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Url) GetForceBlank() bool {
	if x != nil {
		return x.ForceBlank
	}
	return false
}

var File_syrius_common_syrius_ui_common_proto protoreflect.FileDescriptor

var file_syrius_common_syrius_ui_common_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x79, 0x72, 0x69, 0x75, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x73, 0x79, 0x72, 0x69, 0x75, 0x73, 0x5f, 0x75, 0x69, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x79, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x12, 0x66, 0x75, 0x72, 0x6f, 0x2f, 0x66, 0x61, 0x74, 0x2f,
	0x66, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x07, 0x42, 0x69, 0x67,
	0x54, 0x65, 0x78, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x75, 0x72, 0x6f, 0x2e, 0x66, 0x61, 0x74, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x79, 0x0a, 0x0b, 0x42, 0x6f,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x79, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x24, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73,
	0x79, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x72, 0x6c,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0xaa, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x79, 0x72,
	0x69, 0x75, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x32,
	0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x73, 0x79, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42,
	0x6f, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x22, 0x68, 0x0a, 0x08, 0x43, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x79, 0x72,
	0x69, 0x75, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x09, 0x63, 0x6f,
	0x64, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x73, 0x79, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x02,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x61, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x22, 0x62, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12,
	0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x79,
	0x72, 0x69, 0x75, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x64, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0xcf, 0x01, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x54,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x73, 0x79, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x66, 0x6f,
	0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x46,
	0x6f, 0x72, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69,
	0x63, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73,
	0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x73, 0x5f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x22, 0x6b, 0x0a, 0x07, 0x53, 0x79, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x73, 0x79, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x5f, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f,
	0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x6f, 0x72,
	0x63, 0x65, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x42, 0xaf, 0x01, 0x0a, 0x3c, 0x63, 0x6f, 0x6d, 0x2e,
	0x61, 0x64, 0x63, 0x75, 0x62, 0x75, 0x6d, 0x2e, 0x73, 0x79, 0x72, 0x2e, 0x73, 0x79, 0x72, 0x69,
	0x75, 0x73, 0x2e, 0x75, 0x69, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x73, 0x79, 0x72, 0x69, 0x75,
	0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x42, 0x15, 0x53, 0x79, 0x72, 0x69, 0x75, 0x73,
	0x5f, 0x75, 0x69, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x56, 0x67, 0x69, 0x74, 0x2e, 0x61, 0x64, 0x63, 0x75, 0x62, 0x75, 0x6d, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x72, 0x2f, 0x73, 0x79, 0x72, 0x69, 0x75, 0x73, 0x2d, 0x75, 0x69,
	0x2d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2d, 0x62, 0x66, 0x66, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x2f,
	0x70, 0x62, 0x2f, 0x73, 0x79, 0x72, 0x69, 0x75, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_syrius_common_syrius_ui_common_proto_rawDescOnce sync.Once
	file_syrius_common_syrius_ui_common_proto_rawDescData = file_syrius_common_syrius_ui_common_proto_rawDesc
)

func file_syrius_common_syrius_ui_common_proto_rawDescGZIP() []byte {
	file_syrius_common_syrius_ui_common_proto_rawDescOnce.Do(func() {
		file_syrius_common_syrius_ui_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_syrius_common_syrius_ui_common_proto_rawDescData)
	})
	return file_syrius_common_syrius_ui_common_proto_rawDescData
}

var file_syrius_common_syrius_ui_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_syrius_common_syrius_ui_common_proto_goTypes = []interface{}{
	(*BigText)(nil),     // 0: syrius.common.BigText
	(*BoReference)(nil), // 1: syrius.common.BoReference
	(*Code)(nil),        // 2: syrius.common.Code
	(*CodeList)(nil),    // 3: syrius.common.CodeList
	(*Id)(nil),          // 4: syrius.common.Id
	(*Language)(nil),    // 5: syrius.common.Language
	(*SubTenant)(nil),   // 6: syrius.common.SubTenant
	(*SyrUser)(nil),     // 7: syrius.common.SyrUser
	(*Url)(nil),         // 8: syrius.common.Url
	(*fat.String)(nil),  // 9: furo.fat.String
}
var file_syrius_common_syrius_ui_common_proto_depIdxs = []int32{
	9,  // 0: syrius.common.BigText.text:type_name -> furo.fat.String
	4,  // 1: syrius.common.BoReference.id:type_name -> syrius.common.Id
	8,  // 2: syrius.common.BoReference.url:type_name -> syrius.common.Url
	1,  // 3: syrius.common.Code.id:type_name -> syrius.common.BoReference
	1,  // 4: syrius.common.Code.parent:type_name -> syrius.common.BoReference
	1,  // 5: syrius.common.CodeList.id:type_name -> syrius.common.BoReference
	2,  // 6: syrius.common.CodeList.code_list:type_name -> syrius.common.Code
	4,  // 7: syrius.common.Language.id:type_name -> syrius.common.Id
	4,  // 8: syrius.common.SubTenant.id:type_name -> syrius.common.Id
	4,  // 9: syrius.common.SyrUser.id:type_name -> syrius.common.Id
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_syrius_common_syrius_ui_common_proto_init() }
func file_syrius_common_syrius_ui_common_proto_init() {
	if File_syrius_common_syrius_ui_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_syrius_common_syrius_ui_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BigText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syrius_common_syrius_ui_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syrius_common_syrius_ui_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Code); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syrius_common_syrius_ui_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syrius_common_syrius_ui_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syrius_common_syrius_ui_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Language); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syrius_common_syrius_ui_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubTenant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syrius_common_syrius_ui_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyrUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syrius_common_syrius_ui_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Url); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_syrius_common_syrius_ui_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_syrius_common_syrius_ui_common_proto_goTypes,
		DependencyIndexes: file_syrius_common_syrius_ui_common_proto_depIdxs,
		MessageInfos:      file_syrius_common_syrius_ui_common_proto_msgTypes,
	}.Build()
	File_syrius_common_syrius_ui_common_proto = out.File
	file_syrius_common_syrius_ui_common_proto_rawDesc = nil
	file_syrius_common_syrius_ui_common_proto_goTypes = nil
	file_syrius_common_syrius_ui_common_proto_depIdxs = nil
}
